name: NPM Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.2]
        npm-version: [8.5.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          scope: "@busshi"
          always-auth: true
          token: ${{ secrets.NPM_TOKEN }}
          cache: "npm"
          cache-version: ${{ matrix.npm-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish Package
        run: npm publish --access public
